### ISSUE TITLE
can not get the paper result

### ISSUE THREAD

**Issue by softmicro929** [knowledgedefinednetworking/a-deep-rl-approach-for-sdn-routing-optimization#3]
have you anyone get the fig2 result in paper? my model doesn't convergence。

**Comment by etleader** [comment]
> have you anyone get the fig2 result in paper? my model doesn't convergence。

I hava the same question, what's your specific condition? When i train the model, the reward almost don't change. When i test the TMs, i find the training as if never learned sth.

**Comment by softmicro929** [comment]
> > have you anyone get the fig2 result in paper? my model doesn't convergence。
> 
> I hava the same question, what's your specific condition? When i train the model, the reward almost don't change. When i test the TMs, i find the training as if never learned sth.

yes, learn nothing, but you should fix the TM when testing over the training stage

**Comment by etleader** [comment]
> > > have you anyone get the fig2 result in paper? my model doesn't convergence。
> > 
> > 
> > I hava the same question, what's your specific condition? When i train the model, the reward almost don't change. When i test the TMs, i find the training as if never learned sth.
> 
> yes, learn nothing, but you should fix the TM when testing over the training stage

Sorry to bother you, i don't really understand what u mean? How to fix the TMs?

**Comment by softmicro929** [comment]
> > > > have you anyone get the fig2 result in paper? my model doesn't convergence。
> > > 
> > > 
> > > I hava the same question, what's your specific condition? When i train the model, the reward almost don't change. When i test the TMs, i find the training as if never learned sth.
> > 
> > 
> > yes, learn nothing, but you should fix the TM when testing over the training stage
> 
> Sorry to bother you, i don't really understand what u mean? How to fix the TMs?

the author's code didn't do testing , so you have to write test code by yourself to get the fig result in paper.

**Comment by Lui-Chiho** [comment]
> have you anyone get the fig2 result in paper? my model doesn't convergence。

Sorry to bother you！
Have You get the Fig. 1 result ? I still can't understand how to use the TMs mentioned in the paper to train this DRL-Agent . Can you explain the whole training process, because in the given code , I did not find any correlation between the previous state and the new state, It seems that they are all randomly generated using np.random.

**Comment by wqhcug** [comment]
> > have you anyone get the fig2 result in paper? my model doesn't convergence。
> 
> Sorry to bother you！
> Have You get the Fig. 1 result ? I still can't understand how to use the TMs mentioned in the paper to train this DRL-Agent . Can you explain the whole training process, because in the given code , I did not find any correlation between the previous state and the new state, It seems that they are all randomly generated using np.random.

Excuse me. Also have similar  question, I can't understand why the state(TMs) and the new_state(TMs) are  randomly generated  in the step function which in Environment.py .It isn't meeting the logic of DRL.

**Comment by FaisalNaeem1990** [comment]
Can any get the result of the same as in paper as the model is not converging

**Comment by CZMG** [comment]
I have the same question. I dont't understand why the old state and the new state are randomly generated in the Environment.py.

**Comment by FaisalNaeem1990** [comment]
Did you run the whole simulations or not.

**Comment by wqhcug** [comment]
> I have the same question. I dont't understand why the old state and the new state are randomly generated in the Environment.py.
> Did you run the whole simulations or not.
> […](#)

Excuse me. I run the whole simulations. But in my daily study, the STATE of Reinforcement Learning is usually changed by the ACTION, but in the code of this paper, we can find flie that in Environment.py, its NEW STATE and OLD STATE  are randomly generated,  which does not seem to meet the logic of Reinforcement Learning.  Which teacher can answer my confusion? Thank you very much.

**Comment by akaljotdhillon** [comment]
> have you anyone get the fig2 result in paper? my model doesn't convergence。

I am having issue loading the weight. It say Cannot load weight. How to resolve this and where to keep traffic folder?

**Comment by ljh14** [comment]
> > I have the same question. I dont't understand why the old state and the new state are randomly generated in the Environment.py.
> > Did you run the whole simulations or not.
> > […](#)
> 
> Excuse me. I run the whole simulations. But in my daily study, the STATE of Reinforcement Learning is usually changed by the ACTION, but in the code of this paper, we can find flie that in Environment.py, its NEW STATE and OLD STATE are randomly generated, which does not seem to meet the logic of Reinforcement Learning. Which teacher can answer my confusion? Thank you very much.

I've also found this question. I think that the author need to do some explanations. It disobey the basic logic of reinforcement learning. @gissimo

**Comment by slblbwl** [comment]
hello，Please ask how I can run the whole simulation, can you tell me the approximate steps, thank you very much！
